;; -*- mode: eask; lexical-binding: t -*-

(package "org-ticketflow"
         "1.0.0"
         "Two-way sync between Org-mode and your ticketing system")

(website-url "https://github.com/leemw1977/org-ticketflow")
(keywords "org" "jira" "tools" "tickets")

(package-file "org-ticketflow.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "27.1")
(depends-on "plz" "0.3")
